import { z } from "zod";

export const criarServiceSchema = z.object({
  titulo: z.string().min(5, "Título deve ter pelo menos 5 caracteres"),
  descricao: z.string().max(2000, "Descrição pode ter no máximo 2000 caracteres").optional(),
  categoria: z.string().optional(),
  subcategoria: z.string().optional(),
  objetivo: z.string().optional(),
  preco: z.number().positive().nullable().optional(),
  valor_minimo: z.number().positive().nullable().optional(),
  valor_maximo: z.number().positive().nullable().optional(),
  orcamento_definido: z.boolean().optional(),
  aceita_propostas: z.boolean().optional(),
  urgente: z.boolean().optional(),
  urgencia_nivel: z.string().optional(),
  data_inicio_desejada: z.string().optional(),
  data_limite: z.string().optional(),
  tipo_atendimento: z.string().optional(),
  contato: z.string().optional(),
  nome_contratante: z.string().optional(),
  telefone: z.string().optional(),
  whatsapp: z.string().optional(),
  email_contato: z.string().email().optional(),
  localizacao: z.string().optional(),
  endereco: z.string().optional(),
  cidade: z.string().optional(),
  estado: z.string().optional(),
  cep: z.string().optional(),
  referencia_local: z.string().optional(),
  fotos: z.array(z.string()).optional(),
  anexos: z.array(z.string()).optional(),
  detalhes: z.any().optional(),
});
